version: '2'

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - ./data:/home

  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.1
    environment:
      ELASTICSEARCH_URL: http://elastic:9200
      ELASTICSEARCH_HOSTS: '["http://elastic:9200"]'    
    ports:
      - 5601:5601      

      # https://www.elastic.co/guide/en/kibana/7.12/docker.html